swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all API endpoints propositions for user transactions
  version: '2.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /accounts/{userId}:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts Module
      summary: Get all user's accounts
      description: Returns all user's accounts into an array
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: userId
          description: ID of user
          required: true
          type: string
      responses:
        '200':
          description: User accounts retrieved successfully
          schema:
            $ref: '#/definitions/ApiAccountsResponse'
        '400':
          description: Invalid Id supplied
        '401':
          description: Unauthorized
        '404':
          description: Accounts not found
        '500':
          description: Internal Server Error

  /accounts/{userId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Get all user's transactions
      description: Returns all user's transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: userId
          description: ID of user
          required: true
          type: string
      responses:
        '200':
          description: User account transactions retrieved successfully
          schema:
            $ref: '#/definitions/ApiTransactionsResponse'
        '400':
          description: Invalid Id supplied
        '401':
          description: Unauthorized
        '404':
          description: transactions not found
        '500':
          description: Internal Server Error

  /accounts/{idAccount}/transactions/{month}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Get all user's transactions of an account, for specific month
      description: Returns all user's transactions of an account into an array, for specific month
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: idAccount
          description: ID of account
          required: true
          type: string
        - in: path
          name: month
          description: Month of transactions to view
          required: true
          type: string

      responses:
        '200':
          description: User account transactions retrieved successfully
          schema:
            $ref: '#/definitions/ApiTransactionsResponse'
        '400':
          description: Invalid Id supplied
        '401':
          description: Unauthorized
        '404':
          description: transactions not found
        '500':
          description: Internal Server Error

  # /accounts/transaction:
  # post:
  #   security:
  #     - Bearer: []
  #   tags:
  #     - Transaction Module
  #   summary: Post a transaction to user account
  #   description: Add a transaction to user account
  #   parameters:
  #     - in: header
  #       name: Authorization
  #       description: Attach Bearer JWT token
  #       required: true
  #       type: string
  #     - in: body
  #       name: body
  #       description: Transaction info needed to create a new transaction
  #       required: true
  #       schema:
  #         $ref: '#/definitions/PostTransaction'
  #   responses:
  #     '201':
  #       description: Transaction added successfully
  #       schema:
  #         $ref: '#/definitions/ApiTransactionResponse'
  #     '400':
  #       description: Invalid Fields
  #     '401':
  #       description: Unauthorized
  #     '500':
  #       description: Internal Server Error
  /accounts/transaction/{idTransaction}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get a user's transaction
      description: Returns one user's transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: idTransaction
          in: path
          description: ID of transaction
          required: true
          type: string
      responses:
        '200':
          description: User transaction retrieved successfully
          schema:
            $ref: '#/definitions/ApiTransactionResponse'
        '400':
          description: Invalid Id supplied
        '401':
          description: Unauthorized
        '404':
          description: transaction not found
        '500':
          description: Internal Server Error
    # put:
    #   security:
    #     - Bearer: []
    #   tags:
    #     - Accounts Module
    #   summary: Update a user's transaction informations (category or notes)
    #   description: Returns one user's transaction
    #   parameters:
    #     - in: header
    #       name: Authorization
    #       description: Attach Bearer JWT token
    #       required: true
    #       type: string
    #     - name: idTransaction
    #       in: path
    #       description: ID of transaction
    #       required: true
    #       type: string
    #     - in: body
    #       name: body
    #       description: Add transaction category
    #       required: true
    #       schema:
    #         $ref: '#/definitions/EditTransaction'
    #   responses:
    #     '200':
    #       description: User transaction updated successfully
    #       schema:
    #         $ref: '#/definitions/ApiTransactionResponse'
    #     '400':
    #       description: Invalid Id supplied
    #     '401':
    #       description: Unauthorized
    #     '404':
    #       description: transaction not found
    #     '500':
    #       description: Internal Server Error

    # delete:
    #   security:
    #     - Bearer: []
    #   tags:
    #     - Accounts Module
    #   summary: Delete a user's transaction
    #   description: Delete one user transaction
    #   parameters:
    #     - in: header
    #       name: Authorization
    #       description: Attach Bearer JWT token
    #       required: true
    #       type: string
    #     - name: idTransaction
    #       in: path
    #       description: ID of transaction
    #       required: true
    #       type: string
    #   responses:
    #     '204':
    #       description: User account transaction deleted successfully
    #       schema:
    #         $ref: '#/definitions/ApiDeleteResponse'
    #     '400':
    #       description: Invalid Fields
    #     '401':
    #       description: Unauthorized
    #     '500':
    #       description: Internal Server Error

  /accounts/transaction/{idTransaction}/category:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Category Module
      summary: Update category of a transaction
      description: Returns one user's transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: idTransaction
          in: path
          description: ID of transaction
          required: true
          type: string
        - in: body
          name: body
          description: update transaction category
          required: true
          schema:
            $ref: '#/definitions/APICategoryTransaction'
      responses:
        '200':
          description: User account transaction category updated successfully
          schema:
            $ref: '#/definitions/ApiTransactionResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /accounts/transaction/{idTransaction}/notes:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Notes Module
      summary: Create note for a transaction
      description: Returns one user's transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: idTransaction
          in: path
          description: ID of transaction
          required: true
          type: string
        - in: body
          name: body
          description: Add transaction notes
          required: true
          schema:
            $ref: '#/definitions/APINotesTransaction'
      responses:
        '201':
          description: User account transaction notes created successfully
          schema:
            $ref: '#/definitions/ApiTransactionResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /accounts/transaction/{idTransaction}/notes/{noteId}:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Notes Module
      summary: Update note of a transaction
      description: Returns one user's transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: idTransaction
          description: ID of transaction
          required: true
          type: string
        - in: path
          name: noteId
          description: ID of note
          required: true
          type: string
        - in: body
          name: body
          description: update transaction notes
          required: true
          schema:
            $ref: '#/definitions/APINotesTransaction'
      responses:
        '200':
          description: User account transaction notes updated successfully
          schema:
            $ref: '#/definitions/ApiTransactionResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Notes Module
      summary: Delete note of a transaction
      description: API for deleted note of a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: idTransaction
          in: path
          description: ID of transaction
          required: true
          type: string
        - in: path
          name: noteId
          description: ID of note
          required: true
          type: string
      responses:
        '204':
          description: User account note deleted successfully
          schema:
            $ref: '#/definitions/ApiTransactionResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Account:
    type: object
    properties:
      userId:
        type: string
        description: Id of the user owner account
      accountId:
        type: string
        description: Id of account
      title:
        type: string
        description: Title of the account
      amount:
        type: number
        format: float
        description: Amount in the account
      description:
        type: string
        description: Description of the account balance
  Transaction:
    type: object
    properties:
      accountId:
        type: string
        description: Referrer account id
      transactionId:
        type: string
        description: Id of transaction
      date:
        type: string
        format: date
        description: Date of transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        format: float
        description: Amount of the transaction
      type:
        type: string
        description: Type of the transaction
      category:
        type: string
        description: Category of the transaction
      notes:
        type: array
        description: Notes about the transaction
        items:
          type: object
          properties:
            noteId:
              type: string
              description: ID of the note
            content:
              type: string
              description: Content of the note

  # PostTransaction:
  #   type: object
  #   properties:
  #     accountId:
  #       type: string
  #       description: Referrer account id
  #     date:
  #       type: string
  #       format: date
  #       description: Date of transaction
  #     description:
  #       type: string
  #       description: Description of the transaction
  #     amount:
  #       type: number
  #       format: float
  #       description: Amount of the transaction
  #     type:
  #       type: string
  #       description: Type of the transaction
  #     category:
  #       type: string
  #       description: Category of the transaction
  #     notes:
  #       type: array
  #       description: Notes about the transaction
  #       items:
  #         type: object
  #         properties:
  #           noteId:
  #             type: string
  #             description: ID of the note
  #           content:
  #             type: string
  #             description: Content of the note

  APICategoryTransaction:
    type: object
    properties:
      category:
        type: string
        description: Category of the transaction

  APINotesTransaction:
    type: object
    properties:
      note:
        type: string
        description: Note about the transaction

  ApiAccountsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Account'

  ApiTransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction'

  ApiTransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          accountId:
            type: string
            description: Referrer account id
          transactionId:
            type: string
            description: Id of transaction
          date:
            type: string
            format: date
            description: Date of transaction
          description:
            type: string
            description: Description of the transaction
          amount:
            type: number
            format: float
            description: Amount of the transaction
          type:
            type: string
            description: Type of the transaction
          category:
            type: string
            description: Category of the transaction
          notes:
            type: array
            description: Notes about the transaction
            items:
              type: object
              properties:
                noteId:
                  type: string
                  description: ID of the note
                content:
                  type: string
                  description: Content of the note

  ApiDeleteResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
