swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all API endpoints propositions for user transactions
  version: '2.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /accounts/create:
    post:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: create an account
      description: create an account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: account datas
          required: true
          schema:
            $ref: '#/definitions/PostAccount'
      responses:
        '200':
          description: Resource created successfully
          schema:
            $ref: '#/definitions/AccountResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /accounts/{userId}:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Get all user's accounts
      description: Returns all user's accounts into an array
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: userId
          description: ID of user
          required: true
          type: string
      responses:
        '200':
          description: User accounts retrieved successfully
          schema:
            $ref: '#/definitions/AccountsResponse'
        '400':
          description: Invalid Id supplied
        '401':
          description: Unauthorized
        '404':
          description: Accounts not found
        '500':
          description: Internal Server Error

  /transactions/create:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: create a transaction
      description: create a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: transaction datas
          required: true
          schema:
            $ref: '#/definitions/PostTransaction'
      responses:
        '200':
          description: Resource created successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /transactions/{accountId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get all user's transactions of an account for defined month
      description: Returns all user's transactions of an account from defined month
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountId
          description: ID of account
          required: true
          type: string
        - in: query
          name: yearMonth
          description: Month to filter transactions
          format: YYYY-MM
          required: false
          type: string

      responses:
        '200':
          description: User account transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Id supplied
        '401':
          description: Unauthorized
        '404':
          description: transactions not found
        '500':
          description: Internal Server Error

  /transaction/{id}/category:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update category of a transaction
      description: Returns updated user's transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: id
          in: path
          description: ID of transaction
          required: true
          type: string
        - in: body
          name: body
          description: update transaction category
          required: true
          schema:
            $ref: '#/definitions/ApiTransactionCategory'
      responses:
        '200':
          description: User transaction category updated successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /transaction/{id}/notes:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update notes of a transaction
      description: Returns updated user's transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: ID of transaction
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction notes
          required: true
          schema:
            $ref: '#/definitions/ApiTransactionNotes'
      responses:
        '200':
          description: User account transaction notes updated successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /transaction-categories/create:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Category Module
      summary: create a transaction category
      description: create a transaction category
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: transaction category title
          required: true
          schema:
            $ref: '#/definitions/PostTransactionCategory'
      responses:
        '200':
          description: Resource created successfully
          schema:
            $ref: '#/definitions/TransactionCategoryResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /transaction-categories:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Category Module
      summary: Get all transaction categories
      description: Returns all transaction categories
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      responses:
        '200':
          description: Transaction categories retrieved successfully
          schema:
            $ref: '#/definitions/TransactionCategoriesResponse'
        '401':
          description: Unauthorized
        '404':
          description: categories not found
        '500':
          description: Internal Server Error
  /transaction-category/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Category Module
      summary: Get one transaction category
      description: Returns one transaction category
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: ID of category
          required: true
          type: string
      responses:
        '200':
          description: Transaction category retrieved successfully
          schema:
            $ref: '#/definitions/TransactionCategoryResponse'
        '401':
          description: Unauthorized
        '404':
          description: category not found
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Account:
    type: object
    properties:
      _id:
        type: string
        description: Id of account
      userId:
        type: string
        description: Id of the user owner account
      title:
        type: string
        description: Title of the account
      amount:
        type: number
        format: float
        description: Amount in the account
      description:
        type: string
        description: Description of the account balance
  PostAccount:
    type: object
    properties:
      userId:
        type: string
        description: Id of the user owner account
      title:
        type: string
        description: Title of the account
      amount:
        type: number
        format: float
        description: Amount in the account
      description:
        type: string
        description: Description of the account balance
  AccountsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Account'

  AccountResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          _id:
            type: string
            description: Id of account
          userId:
            type: string
            description: Id of the user owner account
          title:
            type: string
            description: Title of the account
          amount:
            type: number
            format: float
            description: Amount in the account
          description:
            type: string
            description: Description of the account balance

  Transaction:
    type: object
    properties:
      _id:
        type: string
        description: Id of transaction
      accountId:
        type: string
        description: Referrer account id
      date:
        type: string
        format: date
        description: Date of transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        format: float
        description: Amount of the transaction
      type:
        type: string
        description: Type of the transaction
      categoryId:
        type: string
        description: ID of transaction category
      notes:
        type: string
        description: notes for transaction

  PostTransaction:
    type: object
    properties:
      accountId:
        type: string
        description: Referrer account id
      date:
        type: string
        format: date
        description: Date of transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        format: float
        description: Amount of the transaction
      type:
        type: string
        description: Type of the transaction
      categoryId:
        type: string
        description: ID of transaction category
      notes:
        type: string
        description: notes for transaction

  TransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction'

  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          _id:
            type: string
            description: Id of transaction
          accountId:
            type: string
            description: Referrer account id
          date:
            type: string
            format: date
            description: Date of transaction
          description:
            type: string
            description: Description of the transaction
          amount:
            type: number
            format: float
            description: Amount of the transaction
          type:
            type: string
            description: Type of the transaction
          categoryId:
            type: string
            description: ID of transaction category
          notes:
            type: string
            description: notes for transaction

  ApiTransactionCategory:
    type: object
    properties:
      categoryId:
        type: string
        description: Id of the transaction category

  ApiTransactionNotes:
    type: object
    properties:
      notes:
        type: string
        description: Notes about the transaction

  TransactionCategory:
    type: object
    properties:
      _id:
        type: string
        description: Id of transaction category
      title:
        type: string
        description: Title of transaction category

  PostTransactionCategory:
    type: object
    properties:
      title:
        type: string
        description: Title of transaction category

  TransactionCategoriesResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/TransactionCategory'

  TransactionCategoryResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          _id:
            type: string
            description: Id of the transaction category
          title:
            type: string
            description: Title of the transaction category
