swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all API endpoints propositions for user transactions
  version: '2.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /accounts/{userId}:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Get all user's accounts
      description: Returns all user's accounts into an array
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: userId
          description: ID of user
          required: true
          type: string
      responses:
        '200':
          description: User accounts retrieved successfully
          schema:
            $ref: '#/definitions/ApiAccountsResponse'
        '400':
          description: Invalid Id supplied
        '401':
          description: Unauthorized
        '404':
          description: Accounts not found
        '500':
          description: Internal Server Error
  /account/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Get one user's accounts
      description: Returns one user's accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: ID of account
          required: true
          type: string
      responses:
        '200':
          description: User account retrieved successfully
          schema:
            $ref: '#/definitions/ApiAccountResponse'
        '400':
          description: Invalid Id supplied
        '401':
          description: Unauthorized
        '404':
          description: Account not found
        '500':
          description: Internal Server Error

  /transactions/{userId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get all user's transactions for defined month
      description: Returns all user's transactions of defined month group by accountId
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: userId
          description: ID of user
          required: true
          type: string
        - in: query
          name: month
          description: Month to filter
          format: YYYY-MM
          required: false
          type: string

      responses:
        '200':
          description: User account transactions retrieved successfully
          schema:
            $ref: '#/definitions/ApiTransactionsResponse'
        '400':
          description: Invalid Id supplied
        '401':
          description: Unauthorized
        '404':
          description: transactions not found
        '500':
          description: Internal Server Error

  /transaction/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get one user's transaction
      description: Returns one user's transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: id
          in: path
          description: ID of transaction
          required: true
          type: string
      responses:
        '200':
          description: User transaction retrieved successfully
          schema:
            $ref: '#/definitions/ApiTransactionResponse'
        '400':
          description: Invalid Id supplied
        '401':
          description: Unauthorized
        '404':
          description: transaction not found
        '500':
          description: Internal Server Error

  /transaction/{id}/category:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update category of a transaction
      description: Returns updated user's transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: id
          in: path
          description: ID of transaction
          required: true
          type: string
        - in: body
          name: body
          description: update transaction category
          required: true
          schema:
            $ref: '#/definitions/APICategoryTransaction'
      responses:
        '200':
          description: User transaction category updated successfully
          schema:
            $ref: '#/definitions/ApiTransactionResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /transaction/{id}/notes:
    # post:
    #   security:
    #     - Bearer: []
    #   tags:
    #     - Transaction Module
    #   summary: Create notes for a transaction
    #   description: Returns user's transaction
    #   parameters:
    #     - in: header
    #       name: Authorization
    #       description: Attach Bearer JWT token
    #       required: true
    #       type: string
    #     - name: id
    #       in: path
    #       description: ID of transaction
    #       required: true
    #       type: string
    #     - in: body
    #       name: body
    #       description: Add transaction notes
    #       required: true
    #       schema:
    #         $ref: '#/definitions/APINotesTransaction'
    #   responses:
    #     '201':
    #       description: User transaction notes created successfully
    #       schema:
    #         $ref: '#/definitions/ApiTransactionResponse'
    #     '400':
    #       description: Invalid Fields
    #     '401':
    #       description: Unauthorized
    #     '500':
    #       description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update notes of a transaction
      description: Returns updated user's transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: ID of transaction
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction notes
          required: true
          schema:
            $ref: '#/definitions/APINotesTransaction'
      responses:
        '200':
          description: User account transaction notes updated successfully
          schema:
            $ref: '#/definitions/ApiTransactionResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /transaction-categories:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Category Module
      summary: Get all transaction categories
      description: Returns all transaction categories
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      responses:
        '200':
          description: Transaction categories retrieved successfully
          schema:
            $ref: '#/definitions/ApiTransactionCategoriesResponse'
        '401':
          description: Unauthorized
        '404':
          description: categories not found
        '500':
          description: Internal Server Error
  /transaction-category/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Category Module
      summary: Get one transaction category
      description: Returns one transaction category
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: ID of category
          required: true
          type: string
      responses:
        '200':
          description: Transaction category retrieved successfully
          schema:
            $ref: '#/definitions/ApiTransactionCategoryResponse'
        '401':
          description: Unauthorized
        '404':
          description: category not found
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Account:
    type: object
    properties:
      id:
        type: string
        description: Id of account
      userId:
        type: string
        description: Id of the user owner account
      title:
        type: string
        description: Title of the account
      amount:
        type: number
        format: float
        description: Amount in the account
      description:
        type: string
        description: Description of the account balance
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Id of transaction
      userId:
        type: string
        description: Referrer user id
      accountId:
        type: string
        description: Referrer account id
      date:
        type: string
        format: date
        description: Date of transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        format: float
        description: Amount of the transaction
      type:
        type: string
        description: Type of the transaction
      categoryId:
        type: string
        description: ID of transaction category
      notes:
        type: string
        description: notes for transaction

  APICategoryTransaction:
    type: object
    properties:
      categoryId:
        type: string
        description: Id of the transaction category

  APINotesTransaction:
    type: object
    properties:
      note:
        type: string
        description: Notes about the transaction

  ApiAccountsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Account'

  ApiTransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            accountId:
              type: string
              description: ID of account
            transactions:
              type: array
              items:
                $ref: '#/definitions/Transaction'

  ApiAccountResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description: Id of account
          userId:
            type: string
            description: Id of the user owner account
          title:
            type: string
            description: Title of the account
          amount:
            type: number
            format: float
            description: Amount in the account
          description:
            type: string
            description: Description of the account balance

  ApiTransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description: Id of transaction
          userId:
            type: string
            description: Referrer user id
          accountId:
            type: string
            description: Referrer account id
          date:
            type: string
            format: date
            description: Date of transaction
          description:
            type: string
            description: Description of the transaction
          amount:
            type: number
            format: float
            description: Amount of the transaction
          type:
            type: string
            description: Type of the transaction
          categoryId:
            type: string
            description: ID of transaction category
          notes:
            type: string
            description: notes for transaction

  ApiTransactionCategoryResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description: Id of the transaction category
          title:
            type: string
            description: Title of the transaction category

  ApiTransactionCategoriesResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              description: Id of the transaction category
            title:
              type: string
              description: Title of the transaction category
